### PR TITLE
Fixed (OS X ?) Problem

### PR DESCRIPTION
**Pull request by pdaether**
Hello @erinata ,

on my Laptop with OS X 10.6.8 the MarkdownBuild plugin did not work.
The html was generated but no browser window popped up.

So i changed the last call and know everything just works. Maybe you want to test this change on windows an push it to your repository.

Greetings
Patrick

### CODE REVIEW

**Comment by erinata** [comment]
I cannot look at it now because I am on the go. But I will look at it and and want to send a BIG THANKS to you. I am not a mac user and I am very grateful that some one help me to make it work in mac.

**Comment by erinata** [comment]
Hey I try that out but it seem that I cannot get it work......

I got 

ImportError: No module named desktop

So it seems that there is nothing named "desktop" for me to import. In the mac version of Sublime Text 2 the python has desktop for importing?

**Comment by pdaether** [comment]
You are right. I had this [lib](http://pypi.python.org/pypi/desktop) on my laptop.

But i had changed the _open_ method again. If you call the `open_url` command not with just the file path but with a complete URI scheme it works on my computer.
Maybe this does the trick?

**Comment by erinata** [comment]
if you use the liburl quote....it doesn't work on windows anymore. 

Can you try the lastest version out on mac?  It use `import webbrowser` and `webbrowser.open("file://"  + output.name)` to do the trick, and it works on both window and linux.

If it still doesn't work on macI guess I can just put a conditional statement to check the platform.

**Comment by pdaether** [comment]
`webbrowser.open`does the trick on osx also without further modifications.
I think we're done.

**Comment by erinata** [comment]
Thanks so much for your help.

**Pull request merged**
